# Generated by Django 4.2.1 on 2023-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order'),
        ),
    ]
